import pandas as pd

bens = pd.read_csv('../dados/bem_candidato_2016_CE.txt', 
                 encoding='ISO-8859-1', 
                 sep=';', 
                 names=["DATA_GERACAO", "HORA_GERACAO", "ANO_ELEICAO", "DESCRICAO_ELEICAO", 
                         "SIGLA_UF", "SQ_CANDIDATO", "CD_TIPO_BEM_CANDIDATO", "TIPO_BEM_CANDIDATO", 
                         "DS_TIPO_BEM_CANDIDATO", "VALOR_BEM", "DATA_ULTIMA_ATUALIZACAO", 
                         "HORA_ULTIMA_ATUALIZACAO"],
                 usecols=["SQ_CANDIDATO", "TIPO_BEM_CANDIDATO", "DS_TIPO_BEM_CANDIDATO", "VALOR_BEM"])

cand = pd.read_csv('../dados/consulta_cand_2016_CE.txt', 
                 encoding='ISO-8859-1', 
                 sep=';',
                 names=["DATA_GERACAO", "HORA_GERACAO", "ANO_ELEICAO", "NUM_TURNO",
                  "DESCRICAO_ELEICAO", "SIGLA_UF", "SIGLA_UE", "DESCRICAO_UE",
                  "CODIGO_CARGO", "DESCRICAO_CARGO", "NOME_CANDIDATO", 
                  "SEQUENCIAL_CANDIDATO", "NUMERO_CANDIDATO",
                  "CPF_CANDIDATO",
                  "NOME_URNA_CANDIDATO", "COD_SITUACAO_CANDIDATURA",
                  "DES_SITUACAO_CANDIDATURA", "NUMERO_PARTIDO", "SIGLA_PARTIDO",
                  "NOME_PARTIDO", "CODIGO_LEGENDA", "SIGLA_LEGENDA", 
                  "COMPOSICAO_LEGENDA", "NOME_LEGENDA", "CODIGO_OCUPACAO",
                  "DESCRICAO_OCUPACAO", "DATA_NASCIMENTO",
                  "NUM_TITULO_ELEITORAL_CANDIDATO", "IDADE_DATA_ELEICAO",
                  "CODIGO_SEXO", "DESCRICAO_SEXO", "COD_GRAU_INSTRUCAO",
                  "DESCRICAO_GRAU_INSTRUCAO", "CODIGO_ESTADO_CIVIL",
                  "DESCRICAO_ESTADO_CIVIL", "CODIGO_COR_RACA",
                  "DESCRICAO_COR_RACA", "CODIGO_NACIONALIDADE",
                  "DESCRICAO_NACIONALIDADE", "SIGLA_UF_NASCIMENTO",
                  "CODIGO_MUNICIPIO_NASCIMENTO", "NOME_MUNICIPIO_NASCIMENTO",
                  "DESPESA_MAX_CAMPANHA", "COD_SIT_TOT_TURNO", 
                  "DESC_SIT_TOT_TURNO", "NM_EMAIL"],
                  usecols=["DESCRICAO_UE", "DESCRICAO_CARGO", "NOME_CANDIDATO",
                           "SEQUENCIAL_CANDIDATO","DES_SITUACAO_CANDIDATURA","SIGLA_PARTIDO",
                           "DESCRICAO_OCUPACAO","IDADE_DATA_ELEICAO","DESCRICAO_SEXO",
                           "DESCRICAO_GRAU_INSTRUCAO","DESCRICAO_ESTADO_CIVIL",
                           "DESCRICAO_COR_RACA","DESCRICAO_NACIONALIDADE",
                           "NOME_MUNICIPIO_NASCIMENTO","DESPESA_MAX_CAMPANHA"])